server:
  port: 8099
spring:
  application:
    name: redis
  redis:
    host: 127.0.0.1
    port: 6379
    # 单机模式
    #    host: 127.0.0.1 #哨兵模式下不用配置
    #    port: 6380 # 哨兵模式下不用配置
    #    # 集群配置
    #    cluster:
    #      nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006
    # 哨兵配置
    # sentinel:
    #  master-name: mymaster
    #  nodes: 127.0.0.1:26380,127.0.0.1:26381
    jedis:
      pool:
        #最大连接数
        max-active: 1024
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 20000
        #最大空闲
        max-idle: 200
        #最小空闲
        min-idle: 10
